name: 'create-deploy-pr'
description: 'Create deployment PR'
inputs:
  githubToken:
    description: "GitHub token"
    required: false
  repoOrg:
    description: "repo org"
    required: false
    default: "VirtoCommerce"
  deployRepo:
    description: "Deployment repository name"
    required: true
    default: "vc-webstore-deploy"
  deployBranch:
    description: "Base branch for new deployment PR"
    required: true
    default: "qa"
  artifactKey:
    description: "ArgoCD config map key for changed artifact"
    required: true
  cmPath:
    description: "Path to config map in repository"
    required: true
    default: "webstore-app/resources/deployment-cm.yaml"

outputs:
  artifactUrl:
    description: "Link to artifact"

runs:
  using: 'node12'
  main: 'dist/index.js' 