name: 'get-artifact-link'
description: 'Gets artifact link from PR comment'
inputs:
  githubToken:
    description: "GitHub token"
    required: false
  repoOrg:
    description: "repo org"
    required: false
    default: "VirtoCommerce"
  deployRepo:
    description: "Deployment repository name"
    required: true
    default: "vc-webstore-deploy"
  deployBranch:
    description: "Base branch for new deployment PR"
    required: true
    default: "qa"

outputs:  
  artifactUrl:
    description: "Link to artifact"

runs:
  using: 'node12'
  main: 'dist/index.js' 