name: 'publish-artifact-link'
description: 'Publishes artifact link to PR comment'
inputs:
  githubToken:
    description: "GitHub token"
    required: false
  repoOrg:
    description: "repo org"
    required: false
    default: "VirtoCommerce"
  artifactUrl:
    description: "Link to artifact"
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js' 