name: 'Update virtocommerce.com/docs'
description: 'Makes and updates documentation for virtocommerce.com/docs'
inputs:
  azureSubscriptionId:
    description: "Azure Subscription ID"
    required: true
  azureResourceGroupName:
    description: "Azure Resource Group Name"
    required: true
  azureWebAppName:
    description: "Azure WebApp Name"
    required: true
  azureTenantId:
    description: ""
    required: true
  azureApiKey:
    description: ""
    required: true
  azureAppId:
    description: ""
    required: true

runs:
  using: "composite"
  steps:
    - name: Preparing
      shell: powershell
      working-directory: ${{ github.workspace }}
      run: |
        & ${{ github.action_path }}/scripts/vc_docs_get_sources.ps1 -ErrorAction Continue

    - name: Build Docs
      working-directory: ${{ github.workspace }}/vc-platform
      shell: powershell
      run: |
        mkdocs build
        7z a ${{ github.workspace }}/site.zip ./site/* -r
        
    - name: Upload docs
      shell: powershell
      env: 
        AzureSubscriptionIDProd: ${{ inputs.azureSubscriptionId }}
        AzureResourceGroupNameProd: ${{ inputs.azureResourceGroupName }}
        AzureWebAppNameProd: ${{ inputs.azureWebAppName }}
        ArtifactPath: ${{ github.workspace }}/site.zip
        AzureAPIKey: ${{ inputs.azureApiKey }}
        AzureTenantID: ${{ inputs.azureTenantId }}
        AzureAppID: ${{ inputs.azureAppId }}
      run: |
        Disable-AzureDataCollection
        ${{ github.action_path }}/scripts/DocsUpdate.ps1
