name: Cloud deployment test
on:
  workflow_dispatch:

jobs:
  deploy:
    uses: VirtoCommerce/.github/.github/workflows/deploy-cloud.yml@main
    with:
      deploymentSource: platform
      releaseType: AzureBlob
      moduleId: "VirtoCommerce.ExperienceApi"
      moduleVer: "3.222.0-alpha.993"
      moduleBlob: "VirtoCommerce.ExperienceApi_3.222.0-alpha.993.zip"
      matrix: '{"include":[{"envName": "qa", "confPath": "argoDeploy.json"}]}'
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}
      argoLogin: ${{ secrets.ARGOCD_LOGIN }}
      argoPassword: ${{ secrets.ARGOCD_PASSWORD }}    