name: Cloud deployment test
on:
  workflow_dispatch:

jobs:
  deploy:
    uses: VirtoCommerce/.github/.github/workflows/deploy-cloud.yml@main
    with:
      deploymentSource: platform
      platformVer: '3.231.0-alpha.12395'
      platformTag: '3.231.0-alpha.12395-dev-5dca7c88'
      matrix: '{"include":[{"envName": "qa", "confPath": "argoDeploy.json"}]}'
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}
      argoLogin: ${{ secrets.ARGOCD_LOGIN }}
      argoPassword: ${{ secrets.ARGOCD_PASSWORD }}    