name: Cloud deployment test
on:
  workflow_dispatch:

jobs:
  deploy:
    # uses: VirtoCommerce/.github/.github/workflows/deploy-cloud.yml@main
    # with:
    #   releaseSource: module
    #   releaseType: GithubReleases
    #   moduleId: "VirtoCommerce.ExperienceApi"
    #   moduleVer: "3.211.4"
    #   matrix: '{"include":[{"envName": "qa", "confPath": "argoDeploy.json"}]}'
    # secrets:
    #   envPAT: ${{ secrets.REPO_TOKEN }}
    #   argoLogin: ${{ secrets.ARGOCD_LOGIN }}
    #   argoPassword: ${{ secrets.ARGOCD_PASSWORD }}    
    uses: VirtoCommerce/.github/.github/workflows/deploy-cloud.yml@v3.200.17
    with:
      releaseSource: module
      moduleId: VirtoCommerce.Catalog
      moduleVer: '3.235.0'
      moduleBlob: 'VirtoCommerce.Catalog_3.235.0.zip'
      jiraKeys: ''
      argoServer: 'argo.virtocommerce.cloud'
      matrix: '{"include":[{"envName":"prod","confPath":".deployment/module/cloudDeploy.json","forceCommit":"true","releaseType":"GithubReleases"},{"envName":"qa","confPath":".deployment/module/cloudDeploy.json","forceCommit":"false","releaseType":"AzureBlob"}]}'
    secrets: inherit

      