name: Cloud deployment test
on:
  workflow_dispatch:

jobs:
  deploy:
    uses: VirtoCommerce/.github/.github/workflows/deploy-cloud.yml@main
    with:
      releaseSource: module
      releaseType: GithubReleases
      moduleId: "VirtoCommerce.ExperienceApi"
      moduleVer: "3.211.4"
      matrix: '{"include":[{"envName": "qa", "confPath": "argoDeploy.json"}]}'
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}
      argoLogin: ${{ secrets.ARGOCD_LOGIN }}
      argoPassword: ${{ secrets.ARGOCD_PASSWORD }}    