name: Deploy argoDeploy config

on:
  workflow_dispatch:

jobs:

  deploy-platform-dev:  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - artifactKey: VirtoCommerce.Assets
          repoName: vc-module-assets
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.AzureblobAssets
          repoName: vc-module-azureblob-assets
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.FilesystemAssets
          repoName: vc-module-filesystem-assets
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.EventBus
          repoName: vc-module-event-bus
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Metadata
          repoName: vc-module-metadata
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Webhooks
          repoName: vc-module-webhooks
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.AuthorizeNet
          repoName: vc-module-Authorize.Net
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.AvalaraTax
          repoName: vc-module-avatax
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.AzureSearch
          repoName: vc-module-azure-search
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.BulkActionsModule
          repoName: vc-module-bulk-actions
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Cart
          repoName: vc-module-cart
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Catalog
          repoName: vc-module-catalog
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.CatalogCsvImportModule
          repoName: vc-module-catalog-csv-import
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.CatalogPersonalization
          repoName: vc-module-catalog-personalization
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.CatalogPublishing
          repoName: vc-module-catalog-publishing
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Content
          repoName: vc-module-content
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Core
          repoName: vc-module-core
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Customer
          repoName: vc-module-customer
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.CustomerReviews
          repoName: vc-module-customer-review
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.DynamicAssociationsModule
          repoName: vc-module-dynamic-associations
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.ElasticSearch
          repoName: vc-module-elastic-search
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.ExperienceApi
          repoName: vc-module-experience-api
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Export
          repoName: vc-module-export
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.GoogleEcommerceAnalytics
          repoName: vc-module-google-ecommerce-analytics
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.ImageTools
          repoName: vc-module-image-tools
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Inventory
          repoName: vc-module-inventory
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.LuceneSearch
          repoName: vc-module-lucene-search
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Marketing
          repoName: vc-module-marketing
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Notifications
          repoName: vc-module-notification
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Orders
          repoName: vc-module-order
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Payment
          repoName: vc-module-payment
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Pricing
          repoName: vc-module-pricing
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Quote
          repoName: vc-module-quote
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Search
          repoName: vc-module-search
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Shipping
          repoName: vc-module-shipping
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Sitemaps
          repoName: vc-module-sitemaps
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Store
          repoName: vc-module-store
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Subscription
          repoName: vc-module-subscription
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Tax
          repoName: vc-module-tax
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.CatalogExportImport
          repoName: vc-module-catalog-export-import
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.CustomerExportImport
          repoName: vc-module-customer-export-import
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.ElasticAppSearch
          repoName: vc-module-elastic-app-search
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.ProfileExperienceApiModule
          repoName: vc-module-profile-experience-api
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.GDPR
          repoName: vc-module-gdpr
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.PriceExportImport
          repoName: vc-module-price-export-import
          configPath: '.deployment/module/argoDeploy.json'

        - artifactKey: VirtoCommerce.Return
          repoName: vc-module-return
          configPath: '.deployment/module/argoDeploy.json'

        # - artifactKey: VirtoCommerce.NotificationsSample
        #   repoName: vc-module-notification
        #   configPath: '.deployment/samples/argoDeploy.json'

        # - artifactKey: VirtoCommerce.CustomerSample
        #   repoName: vc-module-customer
        #   configPath: '.deployment/samples/argoDeploy.json'

        # - artifactKey: VirtoCommerce.OrdersSample
        #   repoName: vc-module-order
        #   configPath: '.deployment/samples/argoDeploy.json'

    steps:
    - name: Update Deploy Config 
      uses: VirtoCommerce/vc-github-actions/update-deploy-config@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        repoName:  ${{ matrix.repoName }}
        artifactKey:  ${{ matrix.artifactKey }}
        configPath: ${{ matrix.configPath }}
