name: Deploy Platform workflows
on:
  workflow_dispatch:

jobs:
  deploy:  
    runs-on: ubuntu-latest
    steps:
    - name: vc-platform
      uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        USER: ${{ env.GITHUB_USER }}
        GHA_DEPLOYMENT_FOLDER: "platform_3_200"
        REPOSITORY: "vc-platform"

