name: Deploy argoDeploy config

on:
  workflow_dispatch:

jobs:

  deploy:  
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
       - repoName: vc-github-actions
         artifactKey: VirtoCommerce.Catalog
    steps:
    - name: Update Deploy Config 
      uses: VirtoCommerce/vc-github-actions/update-deploy-config@PT-4530
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repoName:  ${{ matrix.repoName }}
        branchName: 'PT-4530'
        artifactKey:  ${{ matrix.artifactKey }}
