name: Deploy Github Actions for Demo solution

on:
  workflow_dispatch:

jobs:

  deploy:  
    runs-on: ubuntu-latest
    
    steps:

    ###################################
    #                                 #
    #          Demo solution  CI      #
    #                                 #
    ###################################

    # - name: vc-demo-storefront-ci
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-storefront"
    #     REPOSITORY: "vc-demo-storefront"

    # - name: vc-demo-theme-b2b-ci
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-themes"
    #     REPOSITORY: "vc-demo-theme-b2b"

    # - name: vc-demo-theme-default-ci
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-themes"
    #     REPOSITORY: "vc-demo-theme-default"

    # - name: vc-module-customer-export-import-ci
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-modules"
    #     REPOSITORY: "vc-module-customer-export-import"

    # - name: vc-module-demo-customer-segments-ci
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-modules"
    #     REPOSITORY: "vc-module-demo-customer-segments"

    # - name: vc-module-demo-features-ci
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-modules"
    #     REPOSITORY: "vc-module-demo-features"

    # - name: vc-module-feature-flags-ci
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-modules"
    #     REPOSITORY: "vc-module-feature-flags"

    # - name: vc-module-simple-export-import-ci
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-modules"
    #     REPOSITORY: "vc-module-simple-export-import"

    - name: vc-module-description-export-import-ci
      uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        USER: ${{ env.GITHUB_USER }}
        GHA_DEPLOYMENT_FOLDER: "demo-modules"
        REPOSITORY: "vc-module-description-export-import"


    ###################################
    #                                 #
    #   Demo solution deployment      #
    #                                 #
    ###################################

    # - name: vc-demo-storefront-deployment
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-deployment"
    #     REPOSITORY: "vc-demo-storefront"

    # - name: vc-demo-theme-b2b-deployment
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-deployment"
    #     REPOSITORY: "vc-demo-theme-b2b"

    # - name: vc-demo-theme-default-deployment
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-deployment"
    #     REPOSITORY: "vc-demo-theme-default"

    # - name: vc-module-customer-export-import-deployment
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-deployment"
    #     REPOSITORY: "vc-module-customer-export-import"

    # - name: vc-module-demo-customer-segments-deployment
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-deployment"
    #     REPOSITORY: "vc-module-demo-customer-segments"

    # - name: vc-module-demo-features-deployment
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-deployment"
    #     REPOSITORY: "vc-module-demo-features"

    # - name: vc-module-feature-flags-deployment
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-deployment"
    #     REPOSITORY: "vc-module-feature-flags"

    # - name: vc-module-simple-export-import-deployment
    #   uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    #     USER: ${{ env.GITHUB_USER }}
    #     GHA_DEPLOYMENT_FOLDER: "demo-deployment"
    #     REPOSITORY: "vc-module-simple-export-import"

    - name: vc-module-description-export-import-deployment
      uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        USER: ${{ env.GITHUB_USER }}
        GHA_DEPLOYMENT_FOLDER: "demo-deployment"
        REPOSITORY: "vc-module-description-export-import"
