name: Deploy Module workflows

on:
  workflow_dispatch:

jobs:

  deploy:  
    runs-on: ubuntu-latest
    strategy:
      matrix:
# Module workflows
        deploymentFolder: [platform_3_200]
        repoName: [vc-module-assets
                  ,vc-module-Authorize.Net
                  ,vc-module-avatax
                  ,vc-module-azureblob-assets
                  ,vc-module-azure-search
                  ,vc-module-bulk-actions
                  ,vc-module-cart
                  ,vc-module-catalog
                  ,vc-module-catalog-csv-import
                  ,vc-module-catalog-export-import
                  ,vc-module-catalog-personalization
                  ,vc-module-catalog-publishing
                  ,vc-module-content
                  ,vc-module-contract
                  ,vc-module-core
                  ,vc-module-customer
                  ,vc-module-customer-export-import
                  ,vc-module-customer-review
                  ,vc-module-dynamic-associations
                  ,vc-module-elastic-app-search
                  ,vc-module-elastic-search
                  ,vc-module-event-bus
                  ,vc-module-experience-api
                  ,vc-module-export
                  ,vc-module-filesystem-assets
                  ,vc-module-gdpr
                  ,vc-module-google-ecommerce-analytics
                  ,vc-module-image-tools
                  ,vc-module-inventory
                  ,vc-module-lucene-search
                  ,vc-module-marketing
                  ,vc-module-metadata
                  ,vc-module-notification
                  ,vc-module-order
                  ,vc-module-payment
                  ,vc-module-price-export-import
                  ,vc-module-pricing
                  ,vc-module-profile-experience-api
                  ,vc-module-quote
                  ,vc-module-return
                  ,vc-module-search
                  ,vc-module-shipping
                  ,vc-module-sitemaps
                  ,vc-module-store
                  ,vc-module-subscription
                  ,vc-module-tax
                  ,vc-module-webhooks
                  ,vc-module-native-payment-methods
                  ,vc-module-shipstation
                  ,vc-module-authorize-net]

# Module samples workflows
        # include:
        # - deploymentFolder: modules-sample
        #   repoName: vc-module-order
        # - deploymentFolder: modules-sample
        #   repoName: vc-module-customer
        # - deploymentFolder: modules-sample
        #   repoName: vc-module-notification

    steps:

    - name: Deploy workflows
      uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        USER: ${{ env.GITHUB_USER }}
        GHA_DEPLOYMENT_FOLDER: ${{ matrix.deploymentFolder }}
        REPOSITORY: ${{ matrix.repoName }}
