name: Deploy cloudDeploy config

on:
  workflow_dispatch:

jobs:

  deploy-platform-dev:  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configPath: ['.deployment/module/cloudDeploy.json']
        repoName: [vc-module-assets
                  ,vc-module-Authorize.Net
                  ,vc-module-avatax
                  ,vc-module-azureblob-assets
                  ,vc-module-azure-search
                  ,vc-module-bulk-actions
                  ,vc-module-cart
                  ,vc-module-catalog
                  ,vc-module-catalog-csv-import
                  ,vc-module-catalog-export-import
                  ,vc-module-catalog-personalization
                  ,vc-module-catalog-publishing
                  ,vc-module-content
                  ,vc-module-contract
                  ,vc-module-core
                  ,vc-module-customer
                  ,vc-module-customer-export-import
                  ,vc-module-customer-review
                  ,vc-module-dynamic-associations
                  ,vc-module-elastic-app-search
                  ,vc-module-elastic-search
                  ,vc-module-event-bus
                  ,vc-module-experience-api
                  ,vc-module-export
                  ,vc-module-filesystem-assets
                  ,vc-module-gdpr
                  ,vc-module-google-ecommerce-analytics
                  ,vc-module-image-tools
                  ,vc-module-inventory
                  ,vc-module-lucene-search
                  ,vc-module-marketing
                  ,vc-module-metadata
                  ,vc-module-notification
                  ,vc-module-order
                  ,vc-module-payment
                  ,vc-module-price-export-import
                  ,vc-module-pricing
                  ,vc-module-profile-experience-api
                  ,vc-module-quote
                  ,vc-module-return
                  ,vc-module-search
                  ,vc-module-shipping
                  ,vc-module-sitemaps
                  ,vc-module-store
                  ,vc-module-subscription
                  ,vc-module-tax
                  ,vc-module-webhooks
                  ,vc-module-native-payment-methods
                  ,vc-module-shipstation
                  ,vc-module-authorize-net]

        include:
        - artifactKey: VirtoCommerce.Assets
          repoName: vc-module-assets

        - artifactKey: VirtoCommerce.AzureblobAssets
          repoName: vc-module-azureblob-assets

        - artifactKey: VirtoCommerce.FilesystemAssets
          repoName: vc-module-filesystem-assets

        - artifactKey: VirtoCommerce.EventBus
          repoName: vc-module-event-bus

        - artifactKey: VirtoCommerce.Metadata
          repoName: vc-module-metadata

        - artifactKey: VirtoCommerce.Webhooks
          repoName: vc-module-webhooks

        - artifactKey: VirtoCommerce.AuthorizeNet
          repoName: vc-module-Authorize.Net

        - artifactKey: VirtoCommerce.AvalaraTax
          repoName: vc-module-avatax

        - artifactKey: VirtoCommerce.AzureSearch
          repoName: vc-module-azure-search

        - artifactKey: VirtoCommerce.BulkActionsModule
          repoName: vc-module-bulk-actions

        - artifactKey: VirtoCommerce.Cart
          repoName: vc-module-cart

        - artifactKey: VirtoCommerce.Catalog
          repoName: vc-module-catalog

        - artifactKey: VirtoCommerce.CatalogCsvImportModule
          repoName: vc-module-catalog-csv-import

        - artifactKey: VirtoCommerce.CatalogPersonalization
          repoName: vc-module-catalog-personalization

        - artifactKey: VirtoCommerce.CatalogPublishing
          repoName: vc-module-catalog-publishing

        - artifactKey: VirtoCommerce.Content
          repoName: vc-module-content

        - artifactKey: VirtoCommerce.Core
          repoName: vc-module-core

        - artifactKey: VirtoCommerce.Customer
          repoName: vc-module-customer

        - artifactKey: VirtoCommerce.CustomerReviews
          repoName: vc-module-customer-review

        - artifactKey: VirtoCommerce.DynamicAssociationsModule
          repoName: vc-module-dynamic-associations

        - artifactKey: VirtoCommerce.ElasticSearch
          repoName: vc-module-elastic-search

        - artifactKey: VirtoCommerce.ExperienceApi
          repoName: vc-module-experience-api

        - artifactKey: VirtoCommerce.Export
          repoName: vc-module-export

        - artifactKey: VirtoCommerce.GoogleEcommerceAnalytics
          repoName: vc-module-google-ecommerce-analytics

        - artifactKey: VirtoCommerce.ImageTools
          repoName: vc-module-image-tools

        - artifactKey: VirtoCommerce.Inventory
          repoName: vc-module-inventory

        - artifactKey: VirtoCommerce.LuceneSearch
          repoName: vc-module-lucene-search

        - artifactKey: VirtoCommerce.Marketing
          repoName: vc-module-marketing

        - artifactKey: VirtoCommerce.Notifications
          repoName: vc-module-notification

        - artifactKey: VirtoCommerce.Orders
          repoName: vc-module-order

        - artifactKey: VirtoCommerce.Payment
          repoName: vc-module-payment

        - artifactKey: VirtoCommerce.Pricing
          repoName: vc-module-pricing

        - artifactKey: VirtoCommerce.Quote
          repoName: vc-module-quote

        - artifactKey: VirtoCommerce.Search
          repoName: vc-module-search

        - artifactKey: VirtoCommerce.Shipping
          repoName: vc-module-shipping

        - artifactKey: VirtoCommerce.Sitemaps
          repoName: vc-module-sitemaps

        - artifactKey: VirtoCommerce.Store
          repoName: vc-module-store

        - artifactKey: VirtoCommerce.Subscription
          repoName: vc-module-subscription

        - artifactKey: VirtoCommerce.Tax
          repoName: vc-module-tax

        - artifactKey: VirtoCommerce.CatalogExportImport
          repoName: vc-module-catalog-export-import

        - artifactKey: VirtoCommerce.CustomerExportImport
          repoName: vc-module-customer-export-import

        - artifactKey: VirtoCommerce.ElasticAppSearch
          repoName: vc-module-elastic-app-search

        - artifactKey: VirtoCommerce.ProfileExperienceApiModule
          repoName: vc-module-profile-experience-api

        - artifactKey: VirtoCommerce.GDPR
          repoName: vc-module-gdpr

        - artifactKey: VirtoCommerce.PriceExportImport
          repoName: vc-module-price-export-import

        - artifactKey: VirtoCommerce.Return
          repoName: vc-module-return

        - artifactKey: VirtoCommerce.NativePaymentMethods
          repoName: vc-module-native-payment-methods

        - artifactKey: VirtoCommerce.ShipStation
          repoName: vc-module-shipstation

        - artifactKey: VirtoCommerce.AuthorizeNetPayment
          repoName: vc-module-authorize-net

        - artifactKey: VirtoCommerce.Contracts
          repoName: vc-module-contract



        # - artifactKey: VirtoCommerce.NotificationsSample
        #   repoName: vc-module-notification
        #   configPath: '.deployment/samples/argoDeploy.json'

        # - artifactKey: VirtoCommerce.CustomerSample
        #   repoName: vc-module-customer
        #   configPath: '.deployment/samples/argoDeploy.json'

        # - artifactKey: VirtoCommerce.OrdersSample
        #   repoName: vc-module-order
        #   configPath: '.deployment/samples/argoDeploy.json'

    steps:
    - name: Update Deploy Config 
      uses: VirtoCommerce/vc-github-actions/update-deploy-config@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        repoName:  ${{ matrix.repoName }}
        artifactKey:  ${{ matrix.artifactKey }}
        configPath: ${{ matrix.configPath }}
        deployType: 'cloud'
