name: Deploy Github Actions for Demo solution

on:
  workflow_dispatch:

jobs:

  deploy:  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
# #Demo Storefront workflows
#          - deploymentFolder: demo-storefront
#            repoName: vc-demo-storefront
# #Demo solution deployment workflows
#          - deploymentFolder: demo-deployment
#            repoName: vc-demo-storefront
# #Demo Theme workflows
#          - deploymentFolder: demo-themes
#            repoName: vc-demo-theme-b2b
#          - deploymentFolder: demo-themes
#            repoName: vc-demo-theme-default
#  #Demo solution deployment workflows
#          - deploymentFolder: demo-deployment
#            repoName: vc-demo-theme-b2b
#          - deploymentFolder: demo-deployment
#            repoName: vc-demo-theme-default
#Demo Modules workflows
         - deploymentFolder: demo-modules
           repoName: vc-module-customer-export-import
         - deploymentFolder: demo-modules
           repoName: vc-module-demo-customer-segments
         - deploymentFolder: demo-modules
           repoName: vc-module-demo-features
         - deploymentFolder: demo-modules
           repoName: vc-module-feature-flags
        #  - deploymentFolder: demo-modules
        #    repoName: vc-module-simple-export-import
         - deploymentFolder: demo-modules
           repoName: vc-module-catalog-export-import 
 #Demo solution deployment workflows
         - deploymentFolder: demo-deployment
           repoName: vc-module-customer-export-import
         - deploymentFolder: demo-deployment
           repoName: vc-module-demo-customer-segments
         - deploymentFolder: demo-deployment
           repoName: vc-module-demo-features
         - deploymentFolder: demo-deployment
           repoName: vc-module-feature-flags
        #  - deploymentFolder: demo-deployment
        #    repoName: vc-module-simple-export-import
         - deploymentFolder: demo-deployment
           repoName: vc-module-catalog-export-import 
    steps:
      - name: Deploy workflows
        uses: VirtoCommerce/vc-github-actions/deploy-workflow@master
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          USER: ${{ env.GITHUB_USER }}
          GHA_DEPLOYMENT_FOLDER: ${{ matrix.deploymentFolder }}
          REPOSITORY: ${{ matrix.repoName }}
