name: Docker Environment test
on:
  workflow_dispatch:

jobs:
  docker-env:
    runs-on: ubuntu-18.04

    steps:

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Env
        uses: VirtoCommerce/vc-github-actions/docker-env@master
        with:
          githubUser: ${{ env.GITHUB_ACTOR }}
          githubToken: ${{ env.GITHUB_TOKEN }}
          platformDockerTag: 'linux-latest'
          storefrontDockerTag: 'dev-linux-latest'
          platformImage: ghcr.io/virtocommerce/platform
          storefrontImage: ghcr.io/virtocommerce/storefront
          validateSwagger: 'true'
