name: Publish npm modules
on:
    workflow_dispatch:
    push:
        branches: [ master ]
        paths:
            - 'vc-actions-lib/**'

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Publish vc-actions-lib
          uses: JS-DevTools/npm-publish@v1
          with:
            token: ${{ secrets.NPM_TOKEN }}
            package: ./vc-actions-lib/package.json
            check-version: false