name: Publish npm modules
on:
    workflow_dispatch:
    push:
        branches: [ master ]
        paths:
            - 'vc-actions-lib/**'

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Publish vc-actions-lib
          env:
              NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          shell: bash
          working-directory: vc-actions-lib
          run: |
            npm install -g @jsdevtools/npm-publish
            npm-publish --token $NPM_AUTH_TOKEN
            npm publish --access public