name: test-jira-build

on:
  workflow_dispatch:

jobs:

  push-jira-build:
    runs-on: ubuntu-latest
    env:
      CLOUD_INSTANCE_BASE_URL: ${{secrets.CLOUD_INSTANCE_BASE_URL}}
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      BUILD_STATE: 'successful'
    steps:

    - name: Push Build Info to Jira
      if: ${{ env.CLOUD_INSTANCE_BASE_URL != 0 && env.CLIENT_ID != 0 && env.CLIENT_SECRET != 0 }}
      id: push_build_info_to_jira
      uses: HighwayThree/jira-upload-build-info@master
      with:
        cloud-instance-base-url: '${{ secrets.CLOUD_INSTANCE_BASE_URL }}'
        client-id: '${{ secrets.CLIENT_ID }}'
        client-secret: '${{ secrets.CLIENT_SECRET }}'
        pipeline-id: '${{ github.repository }} ${{ github.workflow }}'
        build-number: ${{ github.run_number }}
        build-display-name: 'Workflow: ${{ github.workflow }} (#${{ github.run_number }})'
        build-state: '${{ env.BUILD_STATE }}'
        build-url: '${{github.event.repository.url}}/actions/runs/${{github.run_id}}'
        update-sequence-number: '${{ github.run_id }}'
        last-updated: '${{github.event.head_commit.timestamp}}'
        issue-keys: 'PT-4254'
        commit-id: '${{ github.sha }}'
        repo-url: '${{ github.event.repository.url }}'
        build-ref-url: '${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}'

    - name: Confirm Jira Build Output
      if: success()
      run: |
        echo "Jira Upload Build Info response: ${{ steps.push_build_info_to_jira.outputs.response }}"
