name: test-fork-pr

on:
  workflow_dispatch:
  push:
    branches:
      [master, dev]
  pull_request:
    branches:
      [master, dev]

jobs:
  ci:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]') }}  # Check that PR not from forked repo and not from Dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Containers info
        shell: pwsh
        run: Write-Host "Test"

