name: "virtocommerce.com docs"
on:
  workflow_dispatch:
  schedule:
    - cron: '30 19 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: Install Dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-awesome-pages-plugin mkdocs-git-revision-date-localized-plugin mkdocs-material mkdocs-minify-plugin mkdocs-redirects pymdown-extensions

      - name: Setup Git Credentials
        uses: VirtoCommerce/vc-github-actions/setup-git-credentials-github@master
        with: 
          githubToken: ${{ secrets.REPO_TOKEN }}

      - name: Update docs
        uses: VirtoCommerce/vc-github-actions/update-virtocommerce-docs@master
        with:
          azureSubscriptionId: ${{ secrets.AZURESUBSCRIPTIONID }}
          azureResourceGroupName: ${{ secrets.AZURERESOURCEGROUPNAME }}
          azureWebAppName: ${{ secrets.AZUREWEBAPPNAME }}
          azureApiKey: ${{ secrets.AZUREAPIKEY }}
          azureTenantId: ${{ secrets.AZURETENANTID }}
          azureAppId: ${{ secrets.AZUREAPPID }}
          dockerRegistry: ${{ secrets.DOCKER_REGISTRY }}
          dockerUsr: ${{ secrets.DOCKER_USER }}
          dockerPwd: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Deploy docs
        uses: VirtoCommerce/vc-github-actions/vc-argocd-cli@master # Uses an action in the root directory
        id: argocd-cli
        with:
          server: argo.govirto.com
          username: ${{ secrets.ARGOCD_LOGIN }}
          password: ${{ secrets.ARGOCD_PASSWORD }}
          command: 'app set vccom-main --helm-set advanced.service.image.tag=${{ env.GITHUB_RUN_NUMBER }}'
