name: "virtocommerce.com docs"
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8.x'

      - name: Install Dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-awesome-pages-plugin mkdocs-git-revision-date-localized-plugin mkdocs-material mkdocs-minify-plugin mkdocs-redirects pymdown-extensions jinja2

      - name: Setup Git Credentials
        uses: VirtoCommerce/vc-github-actions/setup-git-credentials-github@master
        with: 
          githubToken: ${{ secrets.REPO_TOKEN }}

      - name: Update docs
        uses: VirtoCommerce/vc-github-actions/update-virtocommerce-docs@new_docs
        with:
          azureSubscriptionId: ${{ secrets.AZURESUBSCRIPTIONID }}
          azureResourceGroupName: ${{ secrets.AZURERESOURCEGROUPNAME }}
          azureWebAppName: ${{ secrets.AZUREWEBAPPNAME }}
          azureApiKey: ${{ secrets.AZUREAPIKEY }}
          azureTenantId: ${{ secrets.AZURETENANTID }}
          azureAppId: ${{ secrets.AZUREAPPID }}
          dockerRegistry: ${{ secrets.DOCKER_REGISTRY }}
          dockerUsr: ${{ secrets.DOCKER_USER }}
          dockerPwd: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Deploy docs
        uses: VirtoCommerce/vc-github-actions/vc-argocd-cli@master # Uses an action in the root directory
        id: argocd-cli
        with:
          server: argo.govirto.com
          username: ${{ secrets.ARGOCD_LOGIN }}
          password: ${{ secrets.ARGOCD_PASSWORD }}
          command: 'app set tokyo-environment1 --helm-set custom.app1.image.tag=${{ github.run_number }}'
