name: "virtocommerce.com docs"
on:
  workflow_dispatch:
  schedule:
    - cron: '30 19 * * *'

jobs:
  publish:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8.x'

      - name: Install Dependencies
        run: |
          pip install mkdocs==1.1.2
          pip install mkdocs-awesome-pages-plugin==2.2.1 mkdocs-git-revision-date-localized-plugin==0.7 mkdocs-material==5.4.0 mkdocs-minify-plugin==0.3.0 mkdocs-redirects==1.0.1 pymdown-extensions==9.4 jinja2==3.0.3

      - name: Setup Git Credentials
        uses: VirtoCommerce/vc-github-actions/setup-git-credentials-github@master
        with: 
          githubToken: ${{ secrets.REPO_TOKEN }}

      - name: Update docs
        uses: VirtoCommerce/vc-github-actions/update-virtocommerce-docs@new-docs-workflow
        with:
          azureSubscriptionId: ${{ secrets.AZURESUBSCRIPTIONID }}
          azureResourceGroupName: ${{ secrets.AZURERESOURCEGROUPNAME }}
          azureWebAppName: ${{ secrets.AZUREWEBAPPNAME }}
          azureApiKey: ${{ secrets.AZUREAPIKEY }}
          azureTenantId: ${{ secrets.AZURETENANTID }}
          azureAppId: ${{ secrets.AZUREAPPID }}
          dockerRegistry: virtopaasregistrymain.azurecr.io
          dockerUsr: vcpt-repo-saccess
          dockerPwd: 6cWgMnx7PNib50ZrtRxR/gKT7YJBLUrR
  
      - name: Deploy docs
        uses: VirtoCommerce/vc-github-actions/vc-argocd-cli@master # Uses an action in the root directory
        id: argocd-cli
        with:
          server: argocd.govirto.com
          username: admin
          password: BogRz8Zz1-gVONk4
          command: 'app set vcpt-docs --helm-set custom.app1.image.tag=${{ github.run_number }}'
