name: "virtocommerce.com docs"
on:
  workflow_dispatch:
  schedule:
    - cron: '30 19 * * *'
  push:
    paths:
      - ""

jobs:
  publish:
    runs-on: windows-2019

    steps:

      - name: Install Dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-awesome-pages-plugin mkdocs-git-revision-date-localized-plugin mkdocs-material mkdocs-minify-plugin mkdocs-redirects pymdown-extensions

      - name: Setup Git Credentials
        uses: VirtoCommerce/vc-github-actions/setup-git-credentials-github@master
        with: 
          githubToken: ${{ secrets.REPO_TOKEN }}

      - name: Update docs
        working-directory: 
        uses: VirtoCommerce/vc-github-actions/update-virtocommerce-docs@master
        with:
          azureSubscriptionId: ${{ secrets.AZURESUBSCRIPTIONID }}
          azureResourceGroupName: ${{ secrets.AZURERESOURCEGROUPNAME }}
          azureWebAppName: ${{ secrets.AZUREWEBAPPNAME }}
          azureApiKey: ${{ secrets.AZUREAPIKEY }}
          azureTenantId: ${{ secrets.AZURETENANTID }}
          azureAppId: ${{ secrets.AZUREAPPID }}
