name: "virtocommerce.com docs"
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-2019

    steps:

      - name: mkdocs install
        run: pip install mkdocs

      - name: Setup Git Credentials
        uses: VirtoCommerce/vc-github-actions/setup-git-credentials-github@master
        with: 
          githubToken: ${{ secrets.REPO_TOKEN }}

      - name: Update docs
        uses: VirtoCommerce/vc-github-actions/update-virtocommerce-docs@master
        with:
          azureSubscriptionId: ${{ secrets.AZURESUBSCRIPTIONID }}
          azureResourceGroupName: ${{ secrets.AZURERESOURCEGROUPNAME }}
          azureWebAppName: ${{ secrets.AZUREWEBAPPNAME }}
          azureApiKey: ${{ secrets.AZUREAPIKEY }}
          azureTenantId: ${{ secrets.AZURETENANTID }}
          azureAppId: ${{ secrets.AZUREAPPID }}
